chr_id_embed_size: 2
chr_len: 288095
config_base: config.yaml
config_file: /home/kevindsouza/Documents/projects/hic_lstm/src/saved_model/model_lstm/config.yaml
diag_lstm: false
distance_cut: true
distance_cut_off_mb: 100
downstream_dir: /data2/hic_lstm/downstream
hic_path: /data2/hic_lstm/data/
hidden_size_lstm: 8
input_size_lstm: 32
learning_rate: 0.01
load_weights: false
long_shot_sep: false
long_shot_thresh: 1000
lstm_nontrain: false
max_norm: 10
model_dir: /home/kevindsouza/Documents/projects/hic_lstm/src/saved_model/model_lstm
network: lstm
num_chr: 23
num_epochs: 4
output_size_lstm: 1
pos_embed_size: 16
resolution: 10000
sizes_file: chr_cum_sizes.npy
start_end_file: starts.npy
tensorboard_log_base: t_log
tensorboard_log_path: /home/kevindsouza/Documents/projects/hic_lstm/src/saved_model/model_lstm/t_log
